Working code

diff --git a/opt/cami-evaluate-binning/evaluate-binning b/opt/cami-evaluate-binning/evaluate-binning
--- a/opt/cami-evaluate-binning/evaluate-binning
+++ b/opt/cami-evaluate-binning/evaluate-binning
@@ -17,7 +17,7 @@
 set -o errexit
 set -o nounset
 
-required_programs="ncbitax2sqlite tax2racol confusion-matrix cmat2camistats fasta-seqlen sort md5sum"
+required_programs="ncbitax2sqlite tax2racol confusionmatrix cmat2camistats fasta-seqlen sort md5sum"
 # Check for required programs
 for cmd in $required_programs; do
   if test -z "$(which "$cmd")"; then
@@ -26,50 +26,71 @@ for cmd in $required_programs; do
   fi
 done
 
-# some assertions
-[ "$(cut -d '.' -f 1-2 <<<$bbx_version)" == '0.9' ]  # check biobox definition
-[ -r "$bbx_arguments_1_binning_0_value" ]
-[ -r "$bbx_arguments_0_fasta_value" ]
-[ -d "$bbx_arguments_3_databases_0_value" -a -r "$bbx_arguments_3_databases_0_value/names.dmp" -a -r "$bbx_arguments_3_databases_0_value/nodes.dmp" ]
-
 # functions
-taxonomy_version() { cat "$@" | awk -F '\t' '{if($1 != $3) print $1 "\t" $3}' | LC_COLLATE=C sort -u | md5sum | cut -d ' ' -f 1; }
+taxonomy_version() { cat "$@" | awk -F '\t' '{if($1 != $3) print $1 "\t" $3}' | LC_COLLATE=C sort -u | md5sum | cut -d ' ' -f 1; }  # taxonomy hash
+binning2tax() { cat $@ | grep -v -e '^@' -e '^#' | cut -f 1,2; } # bioboxes.org binning to simple TAB-separated
+
 
 # input variables
 ranks='species,genus,family,order,class,phylum,superkingdom'
-cachedir="$BBX_CACHEDIR"
+cache="$BBX_CACHEDIR"
 fastafile="$bbx_arguments_0_fasta_value"
-gold_taxfile="$bbx_arguments_1_binning_1_value"
-pred_taxfile="$bbx_arguments_1_binning_0_value"
+gold_binningfile="$bbx_arguments_1_binning_0_value"
+pred_binningfile="$bbx_arguments_1_binning_1_value"
 taxdir="$bbx_arguments_3_databases_0_value"
-outtable=""
+outtable="$BBX_MNTDIR/output/eval.tsv"
+
+# some assertions
+if [ ! "$(cut -d '.' -f 1-2 <<<$bbx_version)" == '0.9' ]; then
+  echo "Bioboxes.org input definition is '$bbx_version', not '0.9'."
+  exit 1
+fi
+
+if [ ! -r "$gold_binningfile" ]; then
+  echo "Cannot read input label binning file '$gold_binningfile'."
+  exit 1
+fi
+
+if [ ! -r "$pred_binningfile" ]; then
+  echo "Cannot read input prediction binning file '$pred_binningfile'."
+  exit 1
+fi
+
+if [ ! -r "$fastafile" ]; then
+  echo "Cannot read input FASTA file '$fastafile'."
+  exit 1
+fi
+
+if ! [ -d "$taxdir" -a -r "$taxdir/names.dmp" -a -r "$taxdir/nodes.dmp" ]; then
+  echo "Cannot read input taxonomy in '$taxdir'."
+  exit 1
+fi
+
 
 # cached variables
 taxversion="$(taxonomy_version "$taxdir/nodes.dmp")"
-taxsqlite="$cachedir/ncbi-taxonomy_$taxversion.sqlite"
-gold_version="$(md5sum < "$gold_taxfile")"
-gold_racolfile="$cachedir/gold_$goldversion_$taxversion.racol"
-seqlenfile="$cachedir/gold_$goldversion.seqlen"
+taxsqlite="$cache/ncbi-taxonomy_${taxversion}.sqlite"
+goldversion="$(md5sum < "$gold_binningfile" | cut -d ' ' -f 1)"
+gold_taxfile="$cache/gold_${goldversion}.tax"
+gold_racolfile="$cache/gold_${goldversion}_${taxversion}.racol"
+seqlenfile="$cache/gold_${goldversion}.seqlen"
 
 # temporary variables
+tmpdir="$(mktemp -d)"
+pred_taxfile="$tmpdir/pred.tax"
 pred_racolfile="$tmpdir/pred.racol"
 cmatfile="$tmpdir/pred.cmat"
 
-# go to temporary dir
-tmpdir="$(mktemp -d)"
-cd "$tmpdir" # go to tmpdir
-
-# check input and ref files
-
-
 # refresh cache
 [ ! -r "$taxsqlite" ] && ncbitax2sqlite -dmp "$taxdir" -db "$taxsqlite"
-[ "$gold_racolfile" -ot "$gold_taxfile" ] && tax2racol -t "$sqlitefile" -ranks "$ranks" < "$gold_taxfile" > "$gold_racolfile"
+[ ! -r "$gold_taxfile" ] && binning2tax < "$gold_binningfile" > "$gold_taxfile"
+[ ! -r "$gold_racolfile" ] && tax2racol --taxonomy-backend-file "$taxsqlite" --ranks "$ranks" < "$gold_taxfile" > "$gold_racolfile"
 [ ! -r "$seqlenfile" ] && cat $fastafile | fasta-seqlen > "$seqlenfile"
 
 # generate prediction intermediate files
-tax2racol -t "$sqlitefile" -ranks "$ranks" < "$pred_taxfile" > "$pred_racolfile"
-confusion-matrix --rows "$gold_racolfile" --columns "$pred_racolfile" --weights "$seqlenfile" --matrix-form quadratic --allow-missing-columns > "$cmatfile"
+binning2tax < "$pred_binningfile" > "$pred_taxfile"
+tax2racol --taxonomy-backend-file "$taxsqlite" --ranks "$ranks" < "$pred_taxfile" > "$pred_racolfile"
+confusionmatrix --rows "$gold_racolfile" --columns "$pred_racolfile" --weights "$seqlenfile" --matrix-form quadratic --allow-missing-columns > "$cmatfile"
 
 # write CAMI stats
 cmat2camistats < "$cmatfile" > "$outtable"
